// <auto-generated />
using CurrencyChange.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CurrencyChange.Migrations
{
    [DbContext(typeof(CurrencyChangeContext))]
    partial class CurrencyChangeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CurrencyChange.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten");

                    b.Property<int>("Tygia");

                    b.HasKey("Id");

                    b.ToTable("Currency");

                    b.HasData(
                        new { Id = 1, Ten = "USA", Tygia = 23260 },
                        new { Id = 2, Ten = "EUR", Tygia = 27060 },
                        new { Id = 3, Ten = "AUD", Tygia = 16798 },
                        new { Id = 4, Ten = "JPY", Tygia = 20704 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
